/// <reference types="node" />

/**
 * Bundles the worker entry into a single IIFE and inlines it as a string in
 * `src/worker/worker-source.ts`, so consumers get worker isolation with no
 * extra file to host and no bundler configuration.
 */

import { build } from "tsup";
import { readFileSync, writeFileSync, rmSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const OUT_DIR = resolve(".worker-build");
const TARGET = resolve("src/worker/worker-source.ts");

const HEADER = `/**
 * AUTO-GENERATED by scripts/build-worker.ts — do not edit.
 * Source: src/worker/worker-entry.ts
 */
`;

async function main(): Promise<void> {
  // Reset first: a stale inlined worker would otherwise be bundled into itself.
  writeFileSync(TARGET, `${HEADER}export const WORKER_SOURCE = "";\n`);

  await build({
    entry: { worker: "src/worker/worker-entry.ts" },
    outDir: OUT_DIR,
    format: ["iife"],
    platform: "browser",
    target: "es2020",
    minify: true,
    sourcemap: false,
    dts: false,
    clean: true,
    silent: true,
    noExternal: [/.*/],
  });

  const bundlePath = resolve(OUT_DIR, "worker.global.js");
  if (!existsSync(bundlePath)) throw new Error(`Worker bundle not found at ${bundlePath}`);

  const source = readFileSync(bundlePath, "utf-8");
  writeFileSync(TARGET, `${HEADER}export const WORKER_SOURCE = ${JSON.stringify(source)};\n`);
  rmSync(OUT_DIR, { recursive: true, force: true });

  console.log(`✓ worker inlined (${(source.length / 1024).toFixed(1)} KB)`);
}

main().catch((error) => {
  console.error("✗ worker build failed:", error);
  process.exit(1);
});
