/// <reference types="node" />

import { build } from "tsup";
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { resolve } from "node:path";

async function main() {
  console.log("⚙️  Building worker...");

  await build({
    entry: ["src/worker/api-worker.ts"],
    format: ["iife"],
    globalName: "__FETCHGUARD_WORKER__",
    outDir: "dist/worker",
    minify: true,
    sourcemap: false,
    target: "es2020",
    noExternal: [/.*/],
  });

  const possiblePaths = [
    "dist/worker/api-worker.global.js",
    "dist/worker/api-worker.js",
  ];

  let workerPath = "";
  for (const p of possiblePaths) {
    if (existsSync(resolve(p))) {
      workerPath = resolve(p);
      break;
    }
  }

  if (!workerPath) {
    console.log("Files in dist/worker:", readdirSync(resolve("dist/worker")));
    throw new Error("Worker output not found");
  }

  const workerJs = readFileSync(workerPath, "utf-8");

  const output = `// AUTO-GENERATED by scripts/build-worker.ts — do not edit
// Source: src/worker/api-worker.ts

const WORKER_CODE = ${JSON.stringify(workerJs)};

let _code: string | null = null;

export function getWorkerCode(): string {
  if (_code) return _code;
  _code = WORKER_CODE;
  return _code;
}
`;

  writeFileSync(resolve("src/worker/worker-code.ts"), output);
  console.log(`✅ Worker inlined (${(workerJs.length / 1024).toFixed(1)} KB) → src/worker/worker-code.ts`);
}

main().catch((err) => {
  console.error("❌", err);
  process.exit(1);
});